from __future__ import annotations

import ast
import os
import re
from pathlib import Path
from typing import Any, Dict, List, Optional

from atlas_memory.l3_procedural.sleep_baker import StandardProcedure


class SafetyViolationError(Exception):
    """Błąd naruszenia bezpieczeństwa AST w kodzie procedury lub handlera."""
    def __init__(self, violations: List[str], message: Optional[str] = None):
        self.violations = violations
        self.message = message or f"Detected {len(violations)} safety violations in generated code: {violations}"
        super().__init__(self.message)


class ASTSafetyScanner:
    """
    Skaner AST wykrywający niebezpieczne operacje w generowanym lub przekazanym kodzie Python:
    - eval, exec, compile, __import__
    - subprocess.* (call, run, Popen, etc.)
    - os.system, os.popen
    - open() z trybem zapisu ('w', 'a', 'wb', etc.)
    - shutil.rmtree, os.remove, os.unlink
    """

    FORBIDDEN_CALLS = {"eval", "exec", "compile", "__import__"}

    def scan_code(self, code: str) -> List[str]:
        violations: List[str] = []
        try:
            tree = ast.parse(code)
        except SyntaxError as e:
            return [f"SyntaxError on line {e.lineno or 'unknown'}: {e.msg}"]
        except Exception as e:
            return [f"SyntaxError: {str(e)}"]

        for node in ast.walk(tree):
            if isinstance(node, ast.Call):
                lineno = getattr(node, "lineno", 0)
                # 1. Bare forbidden functions (e.g. eval, exec, compile, __import__)
                if isinstance(node.func, ast.Name) and node.func.id in self.FORBIDDEN_CALLS:
                    violations.append(f"Line {lineno}: unsafe call to {node.func.id}")

                # 2. Attribute calls (e.g. os.system, subprocess.run, shutil.rmtree, etc.)
                elif isinstance(node.func, ast.Attribute):
                    attr_name = node.func.attr
                    # Check caller base name if available (e.g., os.system, subprocess.Popen)
                    base_name = ""
                    if isinstance(node.func.value, ast.Name):
                        base_name = node.func.value.id

                    full_call = f"{base_name}.{attr_name}" if base_name else attr_name

                    if base_name == "os" and attr_name in {"system", "popen", "remove", "unlink"}:
                        violations.append(f"Line {lineno}: unsafe call to {full_call}")
                    elif base_name == "subprocess":
                        violations.append(f"Line {lineno}: unsafe call to {full_call}")
                    elif base_name == "shutil" and attr_name in {"rmtree"}:
                        violations.append(f"Line {lineno}: unsafe call to {full_call}")
                    elif attr_name in {"system", "popen", "rmtree", "unlink"}:
                        violations.append(f"Line {lineno}: unsafe call to {full_call}")

                # 3. open() with dangerous write modes ('w', 'a', 'wb', 'ab', 'w+', 'a+')
                if isinstance(node.func, ast.Name) and node.func.id == "open":
                    # Check positional args: open(file, 'w')
                    mode_val = None
                    if len(node.args) >= 2:
                        second_arg = node.args[1]
                        if isinstance(second_arg, ast.Constant) and isinstance(second_arg.value, str):
                            mode_val = second_arg.value
                    # Check keyword args: open(file, mode='w')
                    for kw in node.keywords:
                        if kw.arg == "mode" and isinstance(kw.value, ast.Constant) and isinstance(kw.value.value, str):
                            mode_val = kw.value.value

                    if mode_val and any(m in mode_val for m in ("w", "a", "x", "+")):
                        violations.append(f"Line {lineno}: unsafe call to open with write mode '{mode_val}'")

        return violations


def _sanitize_identifier(name: str) -> str:
    cleaned = re.sub(r"[^0-9a-zA-Z_]", "_", name)
    if not cleaned or cleaned[0].isdigit():
        cleaned = f"proc_{cleaned}"
    return cleaned


def generate_handler(sop: StandardProcedure) -> str:
    """
    Generuje kod Python z klasą Handler, metodami step_N() oraz run()
    realizującymi kroki procedury z izolowaną obsługą błędów.
    """
    class_name = f"{_sanitize_identifier(sop.procedure_id).title().replace('_', '')}Handler"
    if not class_name:
        class_name = "ProcedureHandler"

    lines = [
        '"""',
        f'Autogenerated handler for SOP: {sop.name}',
        f'Procedure ID: {sop.procedure_id}',
        f'Success Rate: {sop.success_rate:.2f} ({sop.invocations_count} runs)',
        '"""',
        "from __future__ import annotations",
        "",
        "import logging",
        "from typing import Any, Dict, List, Optional",
        "",
        "logger = logging.getLogger(__name__)",
        "",
        "",
        f"class {class_name}:",
        f'    """Executable handler for {sop.name}."""',
        "",
        "    def __init__(self, context: Optional[Dict[str, Any]] = None):",
        "        self.context = context or {}",
        "        self.step_results: Dict[str, Any] = {}",
        "",
    ]

    for idx, step in enumerate(sop.steps, start=1):
        step_fn = f"step_{idx}"
        tool_name = step.tool_name
        params = step.params_pattern
        expected = step.expected_outcome or "success"

        lines.extend([
            f"    def {step_fn}(self, **kwargs) -> Dict[str, Any]:",
            f'        """Step {idx}: Execute tool \'{tool_name}\'.',
            f'        Expected outcome: {expected}',
            f'        Default params: {params}',
            '        """',
            f"        logger.info('Executing step {idx}: {tool_name}')",
            "        merged_params = dict(kwargs)",
            f"        default_params = {repr(params)}",
            "        for k, v in default_params.items():",
            "            if k not in merged_params:",
            "                merged_params[k] = v",
            "        try:",
            f"            result = {{'tool': '{tool_name}', 'status': 'completed', 'params': merged_params}}",
            f"            self.step_results['{step_fn}'] = result",
            "            return result",
            "        except Exception as err:",
            f"            logger.error('Error in step {idx} ({tool_name}): %s', err)",
            f"            self.step_results['{step_fn}'] = {{'tool': '{tool_name}', 'status': 'failed', 'error': str(err)}}",
            "            raise",
            "",
        ])

    # Method run()
    lines.extend([
        "    def run(self, **kwargs) -> Dict[str, Any]:",
        '        """Execute all steps sequentially."""',
        "        overall_results: Dict[str, Any] = {}",
    ])

    if not sop.steps:
        lines.append("        return {'status': 'completed', 'steps': {}}")
    else:
        for idx, _ in enumerate(sop.steps, start=1):
            step_fn = f"step_{idx}"
            lines.extend([
                "        try:",
                f"            overall_results['{step_fn}'] = self.{step_fn}(**kwargs)",
                "        except Exception as exc:",
                f"            logger.warning('Execution halted at step {idx}: %s', exc)",
                f"            return {{'status': 'error', 'failed_step': '{step_fn}', 'error': str(exc), 'results': overall_results}}",
            ])
        lines.append("        return {'status': 'completed', 'results': overall_results}")

    return "\n".join(lines) + "\n"


def _generate_skill_md(sop: StandardProcedure) -> str:
    """Generuje zawartość SKILL.md z YAML frontmatter i markdown body."""
    # Build parameters dictionary from step params
    combined_params: Dict[str, Any] = {}
    for step in sop.steps:
        for k, v in step.params_pattern.items():
            combined_params[k] = type(v).__name__ if v is not None else "string"

    yaml_lines = [
        "---",
        f"name: {sop.procedure_id}",
        f"description: {sop.name}",
        "version: 1.0.0",
        f"created_at: {sop.created_at}",
        f"success_rate: {sop.success_rate:.2f}",
        f"invocations_count: {sop.invocations_count}",
        "parameters:",
    ]
    if combined_params:
        for p_name, p_type in combined_params.items():
            yaml_lines.append(f"  {p_name}: {p_type}")
    else:
        yaml_lines.append("  {}")
    yaml_lines.append("---")

    body_lines = [
        "",
        f"# {sop.name}",
        "",
        f"Autonomous procedural skill distilled from {sop.invocations_count} executions (Success rate: {sop.success_rate * 100:.1f}%).",
        "",
        "## Steps",
    ]

    for idx, step in enumerate(sop.steps, start=1):
        outcome_str = f" → Outcome: `{step.expected_outcome}`" if step.expected_outcome else ""
        body_lines.append(f"{idx}. **{step.tool_name}**: parameters `{step.params_pattern}`{outcome_str}")

    body_lines.extend([
        "",
        "## Usage",
        "```python",
        f"from scripts.handler import {_sanitize_identifier(sop.procedure_id).title().replace('_', '')}Handler",
        "",
        f"handler = {_sanitize_identifier(sop.procedure_id).title().replace('_', '')}Handler()",
        "result = handler.run()",
        "```",
        "",
    ])

    return "\n".join(yaml_lines) + "\n" + "\n".join(body_lines)


def compile_sop_to_skill(
    sop: StandardProcedure,
    target_dir: Optional[Path] = None,
    scanner: Optional[ASTSafetyScanner] = None,
) -> Path:
    """
    Kompiluje obiekt StandardProcedure do natywnego skilla Hermes:
    - target_dir/SKILL.md (YAML frontmatter + markdown body)
    - target_dir/scripts/handler.py (Executable class z metodami step_N + run)
    
    Weryfikuje kod pod kątem bezpieczeństwa przez ASTSafetyScanner.
    Jeśli wykryto naruszenia, rzuca SafetyViolationError.
    """
    if target_dir is None:
        target_dir = Path(os.path.expanduser(f"~/.hermes/skills/{sop.procedure_id}"))

    scanner = scanner or ASTSafetyScanner()

    # Sprawdzenie czy w parametrach lub nazwach narzędzi nie ma jawnych wektorów ataku
    for step in sop.steps:
        # Check if step.tool_name or step.params_pattern contains code with safety violations
        for v in step.params_pattern.values():
            if isinstance(v, str):

                violations = scanner.scan_code(v)
                if violations and not any(v.startswith("SyntaxError") for v in violations):
                    raise SafetyViolationError(violations)
        if step.tool_name in scanner.FORBIDDEN_CALLS or step.tool_name in {"os.system", "subprocess", "rmtree"}:
            raise SafetyViolationError([f"Unsafe tool name: {step.tool_name}"])

    handler_code = generate_handler(sop)
    violations = scanner.scan_code(handler_code)
    if violations:
        raise SafetyViolationError(violations)

    skill_md_content = _generate_skill_md(sop)

    # Zapis na dysk
    scripts_dir = target_dir / "scripts"
    scripts_dir.mkdir(parents=True, exist_ok=True)

    skill_md_path = target_dir / "SKILL.md"
    handler_path = scripts_dir / "handler.py"

    skill_md_path.write_text(skill_md_content, encoding="utf-8")
    handler_path.write_text(handler_code, encoding="utf-8")

    return target_dir


def register_in_hermes_environment(
    skill_dir: Path,
    hermes_skills_root: Optional[Path] = None,
    scanner: Optional[ASTSafetyScanner] = None,
) -> Path:
    """
    Rejestruje skompilowany katalog skilla w środowisku Hermesa (~/.hermes/skills/atlas_procedural/<skill_name>).
    
    1. Weryfikuje obecność SKILL.md i scripts/handler.py.
    2. Przeprowadza walidację bezpieczeństwa AST kodu handlera.
    3. Instaluje/aktualizuje pliki w docelowym katalogu.
    4. Zapisuje lub aktualizuje atomiczny manifest skills_manifest.json.
    """
    if hermes_skills_root is None:
        hermes_skills_root = Path(os.environ.get("HERMES_SKILLS_DIR", str(Path.home() / ".hermes" / "skills")))

    target_procedural_root = hermes_skills_root / "atlas_procedural"
    target_procedural_root.mkdir(parents=True, exist_ok=True)

    skill_md = skill_dir / "SKILL.md"
    handler_py = skill_dir / "scripts" / "handler.py"

    if not skill_md.exists():
        raise FileNotFoundError(f"SKILL.md missing in {skill_dir}")
    if not handler_py.exists():
        raise FileNotFoundError(f"scripts/handler.py missing in {skill_dir}")

    scanner = scanner or ASTSafetyScanner()
    handler_code = handler_py.read_text(encoding="utf-8")
    violations = scanner.scan_code(handler_code)
    if violations:
        raise SafetyViolationError(violations)

    skill_name = skill_dir.name
    destination_skill_dir = target_procedural_root / skill_name
    dest_scripts_dir = destination_skill_dir / "scripts"
    dest_scripts_dir.mkdir(parents=True, exist_ok=True)

    import shutil
    shutil.copy2(skill_md, destination_skill_dir / "SKILL.md")
    shutil.copy2(handler_py, dest_scripts_dir / "handler.py")

    # Manifest registration
    import json
    import time
    manifest_path = target_procedural_root / "skills_manifest.json"
    manifest: Dict[str, Any] = {}
    if manifest_path.exists():
        try:
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        except Exception:
            manifest = {}

    manifest[skill_name] = {
        "name": skill_name,
        "path": str(destination_skill_dir),
        "registered_at": time.time(),
        "handler_size_bytes": len(handler_code.encode("utf-8")),
        "status": "active",
    }
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    return destination_skill_dir


def compile_and_register_sop(
    sop: StandardProcedure,
    target_dir: Optional[Path] = None,
    hermes_skills_root: Optional[Path] = None,
    scanner: Optional[ASTSafetyScanner] = None,
) -> Dict[str, Any]:
    """
    Pełny pipeline: Kompiluje SOP do natywnego formatu i rejestruje w katalogu Hermesa.
    """
    compiled_dir = compile_sop_to_skill(sop, target_dir=target_dir, scanner=scanner)
    registered_path = register_in_hermes_environment(
        skill_dir=compiled_dir,
        hermes_skills_root=hermes_skills_root,
        scanner=scanner,
    )
    return {
        "procedure_id": sop.procedure_id,
        "compiled_path": str(compiled_dir),
        "registered_path": str(registered_path),
        "success_rate": sop.success_rate,
        "steps_count": len(sop.steps),
        "registered": True,
    }
