#!/usr/bin/env bash
# scripts/install-hermes-plugin.sh — instaluje ATLAS jako memory provider w Hermes
# Wzorzec: mnemosyne-hermes install --mode wrapper
#
# Użycie:
#   bash scripts/install-hermes-plugin.sh [--activate] [--uninstall]
#
# Efekty:
#   1. Generuje lekki wrapper ~/.hermes/plugins/atlas/{plugin.yaml, __init__.py}
#   2. Izolacja: Silnik ATLAS działa w Pixi (Python 3.14), a plugin w Hermes łączy się przez UDS IPC
#   3. (opcjonalnie) --activate → hermes config set memory.provider atlas
#   4. Weryfikuje: load_memory_provider('atlas') → available=True
#
# Reprodukowalność:
#   hermes upgrade nie dotyka ~/.hermes/venv/ ani ~/.hermes/plugins/ — przetrwa update.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HERMES_VENV="${HERMES_VENV:-$HOME/.hermes/venv}"
HERMES_PLUGINS_DIR="${HERMES_PLUGINS_DIR:-$HOME/.hermes/plugins}"
PLUGIN_NAME="atlas"
PYTHON="${HERMES_VENV}/bin/python3"

# --- args
ACTIVATE=0
UNINSTALL=0
for arg in "$@"; do
  case "$arg" in
    --activate) ACTIVATE=1 ;;
    --uninstall) UNINSTALL=1 ;;
    --help|-h)
      sed -n '2,/^$/s/^# \?//p' "$0"
      exit 0 ;;
    *) echo "Unknown arg: $arg"; exit 2 ;;
  esac
done

log() { printf '→ %s\n' "$*"; }
err() { printf '✗ %s\n' "$*" >&2; }

# --- uninstall (czysty)
if [[ $UNINSTALL -eq 1 ]]; then
  log "Odinstalowywanie pluginu ${PLUGIN_NAME}..."
  rm -rf "${HERMES_PLUGINS_DIR}/${PLUGIN_NAME}"
  log "Czysto. Aby zmienić provider: hermes config set memory.provider mnemosyne"
  exit 0
fi

# --- sanity checks
if [[ ! -x "$PYTHON" ]]; then
  err "Hermes venv nie znaleziony: $PYTHON"
  err "Ustaw HERMES_VENV=/ścieżka/do/venv lub zainstaluj Hermes"
  exit 1
fi
if [[ ! -f "${REPO_ROOT}/pyproject.toml" ]]; then
  err "Nie można znaleźć pyproject.toml w $REPO_ROOT"
  exit 1
fi

# --- 1. Generuj wrapper (Izolacja: Zero zanieczyszczania Hermes venv pakietami C/Rust)
PLUGIN_DIR="${HERMES_PLUGINS_DIR}/${PLUGIN_NAME}"
mkdir -p "$PLUGIN_DIR"

# Backup istniejącego pluginu jeśli jest
if [[ -f "${PLUGIN_DIR}/__init__.py" && ! -d "${PLUGIN_DIR}.bak" ]]; then
  cp -r "$PLUGIN_DIR" "${PLUGIN_DIR}.bak.$(date +%s)"
  log "Backup starego pluginu"
fi

log "Generowanie wrappera do ${PLUGIN_DIR}..."

# plugin.yaml — manifest pluginu
cat > "${PLUGIN_DIR}/plugin.yaml" <<'YAML'
name: atlas
version: 1.0.0
description: "ATLAS Cognitive Memory Sidecar for Hermes — Zero-GIL Python 3.14 Micro-Daemon with Verified KV Ledger, Kùzu Graph, RaBitQ Vector Store, Retro-Causal What-If, and Active Sensing."
author: Dominik Sidorczuk
provides_tools:
  - atlas_recall
  - atlas_remember
  - atlas_what_if
  - atlas_active_sensing
  - atlas_stats
provides_hooks:
  - pre_llm_call
  - on_session_start
dependencies: []
YAML

# __init__.py — wrapper (NO hardcoded paths; imports from Hermes venv + pixi env)
cat > "${PLUGIN_DIR}/__init__.py" <<'PYTHON'
"""Persistent ATLAS Hermes plugin wrapper.

Generated by scripts/install-hermes-plugin.sh. Wrapper keeps the Hermes
discovery directory stable while importing the real ``atlas_memory`` package
installed in the pixi env (site-packages). Survives hermes upgrade.
"""
from __future__ import annotations

import logging
import os
import subprocess
import sys as _sys
import time
from pathlib import Path as _Path

# Metadata used by hermes plugin status/loader.
_PYTHON = '__HERMES_PYTHON__'
_SITE = '__HERMES_SITE__'
_SRC = '__ATLAS_SRC__'
_PIXI_SITE = '__PIXI_SITE__'

if _SITE not in _sys.path:
    _sys.path.append(_SITE)
if _SRC not in _sys.path:
    _sys.path.append(_SRC)
if _PIXI_SITE not in _sys.path:
    _sys.path.append(_PIXI_SITE)

# Hermes discovery marker: register_memory_provider / MemoryProvider
from atlas_memory.hermes.atlas_provider import AtlasMemoryProvider  # noqa: E402,F401

try:
    from agent.memory_provider import MemoryProvider  # noqa: E402,F401
except ImportError:
    MemoryProvider = object  # type: ignore


_SOCKET_PATH = _Path.home() / ".hermes" / "atlas.sock"
_LAUNCHER_SCRIPT = _Path(_SRC).parent / "scripts" / "atlas_daemon_launcher.py"
_PIXI_BIN = _Path.home() / ".pixi" / "bin" / "pixi"
if not _PIXI_BIN.exists():
    _PIXI_BIN = "pixi"


def _is_daemon_alive() -> bool:
    """Verifies that the daemon is actively responding to JSON-RPC ping over UDS."""
    try:
        from atlas_memory.server.client import send_uds_request_sync
        res = send_uds_request_sync(_SOCKET_PATH, method="ping", timeout=0.2)
        return isinstance(res, dict) and res.get("status") == "ok"
    except Exception:
        return False


def _ensure_daemon_running() -> None:
    """Spawns AtlasDaemon in Python 3.14 via Pixi if not already responding."""
    if _is_daemon_alive():
        return
    try:
        logging.getLogger("atlas-plugin").info("Spawning ATLAS daemon in background...")
        try:
            if _SOCKET_PATH.exists():
                _SOCKET_PATH.unlink(missing_ok=True)
            pid_file = _SOCKET_PATH.with_suffix(".pid")
            if pid_file.exists():
                pid_file.unlink(missing_ok=True)
        except Exception:
            pass

        repo_dir = _Path(_SRC).parent
        log_file = _Path.home() / ".hermes" / "atlas" / "daemon.log"
        log_file.parent.mkdir(parents=True, exist_ok=True)
        log_fp = open(str(log_file), "a", encoding="utf-8")
        subprocess.Popen(
            [str(_PIXI_BIN), "run", "python", str(_LAUNCHER_SCRIPT)],
            cwd=str(repo_dir),
            stdout=log_fp,
            stderr=log_fp,
            start_new_session=True,
        )
        for _ in range(40):
            if _is_daemon_alive():
                logging.getLogger("atlas-plugin").info("ATLAS daemon successfully spawned and responding on UDS")
                break
            time.sleep(0.05)
    except Exception as exc:
        logging.getLogger("atlas-plugin").warning("Could not auto-spawn ATLAS daemon: %s", exc)



def register(ctx):
    """Hermes plugin contract — register ATLAS memory provider and first-class tools."""
    try:
        _ensure_daemon_running()
        provider = AtlasMemoryProvider(socket_path=str(_SOCKET_PATH))
        ctx.register_memory_provider(provider)
        logging.getLogger("atlas-plugin").info("ATLAS MemoryProvider successfully registered via UDS (%s)", _SOCKET_PATH)
    except Exception as exc:
        logging.getLogger("atlas-plugin").warning("ATLAS register provider failed: %s", exc)
        ctx.register_memory_provider(AtlasMemoryProvider())

    try:
        from atlas_memory.hermes import tools as _atlas_tools

        handlers = _atlas_tools.create_uds_tool_handlers(socket_path=_SOCKET_PATH)

        if hasattr(ctx, "register_tool"):
            ctx.register_tool(name="atlas_recall", toolset="atlas", schema=_atlas_tools.ATLAS_RECALL_SCHEMA, handler=handlers["atlas_recall"])
            ctx.register_tool(name="atlas_remember", toolset="atlas", schema=_atlas_tools.ATLAS_REMEMBER_SCHEMA, handler=handlers["atlas_remember"])
            ctx.register_tool(name="atlas_what_if", toolset="atlas", schema=_atlas_tools.ATLAS_WHAT_IF_SCHEMA, handler=handlers["atlas_what_if"])
            ctx.register_tool(name="atlas_active_sensing", toolset="atlas", schema=_atlas_tools.ATLAS_ACTIVE_SENSING_SCHEMA, handler=handlers["atlas_active_sensing"])
            ctx.register_tool(name="atlas_stats", toolset="atlas", schema=_atlas_tools.ATLAS_STATS_SCHEMA, handler=handlers["atlas_stats"])
            logging.getLogger("atlas-plugin").info("ATLAS first-class tools registered")
    except Exception as exc:
        logging.getLogger("atlas-plugin").warning("Could not register ATLAS tools in ctx: %s", exc)

PYTHON

# Podstaw realne ścieżki (H4: zero hardcoded wartości)
SITE_PACKAGES=$("$PYTHON" -c 'import site; print(site.getsitepackages()[0])')
# Pixi site-packages — zależności C/Rust ATLAS (numba, kuzu, qdrant_client) żyją w pixi env
PIXI_SITE=""
if command -v pixi >/dev/null 2>&1 && [[ -d "${REPO_ROOT}/.pixi" ]]; then
  PIXI_SITE=$(cd "$REPO_ROOT" && pixi run python -c 'import site; print(site.getsitepackages()[0])' 2>/dev/null | tail -1) || true
fi
sed -i "s|__HERMES_PYTHON__|${PYTHON}|g" "${PLUGIN_DIR}/__init__.py"
sed -i "s|__HERMES_SITE__|${SITE_PACKAGES}|g" "${PLUGIN_DIR}/__init__.py"
sed -i "s|__ATLAS_SRC__|${REPO_ROOT}/src|g" "${PLUGIN_DIR}/__init__.py"
if [[ -n "$PIXI_SITE" && -d "$PIXI_SITE" ]]; then
  sed -i "s|__PIXI_SITE__|${PIXI_SITE}|g" "${PLUGIN_DIR}/__init__.py"
  log "✓ Pixi site-packages podpięte: ${PIXI_SITE}"
else
  sed -i "/__PIXI_SITE__/d" "${PLUGIN_DIR}/__init__.py"
  log "⚠ Pixi site-packages nie znaleziono — lewery C/Rust (numba/kuzu/qdrant) niedostępne"
fi

# Instalacja skillu do ~/.hermes/skills/memory/atlas-cognitive-sidecar/
HERMES_SKILLS_DIR="${HERMES_SKILLS_DIR:-$HOME/.hermes/skills}"
if [[ -d "${REPO_ROOT}/skills/atlas-cognitive-sidecar" ]]; then
  mkdir -p "${HERMES_SKILLS_DIR}/memory/atlas-cognitive-sidecar"
  cp -r "${REPO_ROOT}/skills/atlas-cognitive-sidecar/"* "${HERMES_SKILLS_DIR}/memory/atlas-cognitive-sidecar/"
  log "✓ Skill atlas-cognitive-sidecar zainstalowany w ${HERMES_SKILLS_DIR}/memory/atlas-cognitive-sidecar"
fi

log "✓ Wrapper i Skill wygenerowane"

# --- 2. Aktywuj jeśli zażądano
if [[ $ACTIVATE -eq 1 ]]; then
  log "Aktywacja providera w Hermes config..."
  if command -v hermes >/dev/null 2>&1; then
    hermes config set memory.provider atlas
    log "✓ memory.provider = atlas"
  else
    log "⚠ hermes CLI nie w PATH — ustaw ręcznie: memory.provider: atlas w ~/.hermes/config.yaml"
  fi
fi

# --- 3. Weryfikacja
log "Weryfikacja..."
"$PYTHON" - <<'PYCHECK'
import sys
from pathlib import Path

# Symulacja Hermes plugin loader
plugins_root = Path.home() / ".hermes" / "plugins"
if str(plugins_root) not in sys.path:
    sys.path.append(str(plugins_root))

try:
    # 1. Sprawdź discovery przez hermes provider collector
    try:
        from plugins.memory import discover_memory_providers, load_memory_provider
        providers = discover_memory_providers()
        names = [p[0] for p in providers]
        print(f"  discover: atlas ∈ {len(names)} providers")
        
        provider = load_memory_provider("atlas")
        if provider:
            avail = provider.is_available()
            print(f"  load: atlas, available={avail}")
        else:
            print("  load: atlas -> FAILED (None)")
            sys.exit(1)
    except ImportError:
        # Standalone check bez pełnego hermes-agent w PATH
        import importlib
        mod = importlib.import_module("atlas")
        print(f"  import atlas: OK ({mod.__file__})")

    print("→ ✓ Instalacja OK")
except Exception as e:
    print(f"✗ Weryfikacja nie powiodła się: {e}")
    sys.exit(1)
PYCHECK

echo ""
echo "═══════════════════════════════════════════════════════════"
echo " ATLAS plugin zainstalowany pomyślnie"
echo "═══════════════════════════════════════════════════════════"
echo "  Plugin dir: ${PLUGIN_DIR}"
echo "  Izolacja:   ATLAS silnik działa w Pixi (.pixi/envs/default)"
echo "  Config:     ~/.hermes/config.yaml (memory.provider)"
echo ""
echo "  Aby aktywować:  hermes config set memory.provider atlas"
echo "  Aby odinstalować: bash $0 --uninstall"
echo "  Aby zweryfikować: hermes memory status"
echo ""
