#!/usr/bin/env bash
# scripts/install-hermes-plugin.sh — instaluje ATLAS jako memory provider w Hermes
# Wzorzec: mnemosyne-hermes install --mode wrapper
#
# Użycie:
#   bash scripts/install-hermes-plugin.sh [--activate] [--uninstall]
#
# Efekty:
#   1. Generuje lekki wrapper ~/.hermes/plugins/atlas/{plugin.yaml, __init__.py}
#   2. Izolacja: Silnik ATLAS działa w Pixi (Python 3.14), a plugin w Hermes łączy się przez UDS IPC
#   3. (opcjonalnie) --activate → hermes config set memory.provider atlas
#   4. Weryfikuje: load_memory_provider('atlas') → available=True
#
# Reprodukowalność:
#   hermes upgrade nie dotyka ~/.hermes/venv/ ani ~/.hermes/plugins/ — przetrwa update.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HERMES_VENV="${HERMES_VENV:-$HOME/.hermes/venv}"
HERMES_PLUGINS_DIR="${HERMES_PLUGINS_DIR:-$HOME/.hermes/plugins}"
PLUGIN_NAME="atlas"
PYTHON="${HERMES_VENV}/bin/python3"

# --- args
ACTIVATE=0
UNINSTALL=0
for arg in "$@"; do
  case "$arg" in
    --activate) ACTIVATE=1 ;;
    --uninstall) UNINSTALL=1 ;;
    --help|-h)
      sed -n '2,/^$/s/^# \?//p' "$0"
      exit 0 ;;
    *) echo "Unknown arg: $arg"; exit 2 ;;
  esac
done

log() { printf '→ %s\n' "$*"; }
err() { printf '✗ %s\n' "$*" >&2; }

# --- uninstall (czysty)
if [[ $UNINSTALL -eq 1 ]]; then
  log "Odinstalowywanie pluginu ${PLUGIN_NAME}..."
  rm -rf "${HERMES_PLUGINS_DIR}/${PLUGIN_NAME}"
  log "Czysto. Aby zmienić provider: hermes config set memory.provider mnemosyne"
  exit 0
fi

# --- sanity checks
if [[ ! -x "$PYTHON" ]]; then
  err "Hermes venv nie znaleziony: $PYTHON"
  err "Ustaw HERMES_VENV=/ścieżka/do/venv lub zainstaluj Hermes"
  exit 1
fi
if [[ ! -f "${REPO_ROOT}/pyproject.toml" ]]; then
  err "Nie można znaleźć pyproject.toml w $REPO_ROOT"
  exit 1
fi

# --- 1. Generuj wrapper (Izolacja: Zero zanieczyszczania Hermes venv pakietami C/Rust)
PLUGIN_DIR="${HERMES_PLUGINS_DIR}/${PLUGIN_NAME}"
mkdir -p "$PLUGIN_DIR"

# Backup istniejącego pluginu jeśli jest
if [[ -f "${PLUGIN_DIR}/__init__.py" && ! -d "${PLUGIN_DIR}.bak" ]]; then
  cp -r "$PLUGIN_DIR" "${PLUGIN_DIR}.bak.$(date +%s)"
  log "Backup starego pluginu"
fi

log "Generowanie wrappera do ${PLUGIN_DIR}..."

# plugin.yaml — manifest pluginu
cat > "${PLUGIN_DIR}/plugin.yaml" <<'YAML'
name: atlas
version: 0.1.0
description: "ATLAS Memory Provider for Hermes — 6 levers of memory policy orchestrating Mnemosyne store with cache contracts, epistemic ranking, and shadow reconciliation."
author: LOOP Team
provides_hooks:
  - pre_llm_call
  - on_session_start
dependencies: []
YAML

# __init__.py — wrapper (NO hardcoded paths; imports from Hermes venv)
cat > "${PLUGIN_DIR}/__init__.py" <<'PYTHON'
"""Persistent ATLAS Hermes plugin wrapper.

Generated by scripts/install-hermes-plugin.sh. Wrapper keeps the Hermes
discovery directory stable while importing the real ``loop_memory`` package
installed in the Hermes venv (site-packages). Survives hermes upgrade.
"""
from __future__ import annotations

import sys as _sys
from pathlib import Path as _Path

# Metadata used by hermes plugin status/loader.
_PYTHON = '__HERMES_PYTHON__'
_SITE = '__HERMES_SITE__'
_SRC = '__ATLAS_SRC__'

if _SITE not in _sys.path:
    _sys.path.append(_SITE)
if _SRC not in _sys.path:
    _sys.path.append(_SRC)

# Hermes discovery marker: register_memory_provider / MemoryProvider
from loop_memory.hermes.atlas_provider import AtlasMemoryProvider  # noqa: E402,F401

try:
    from agent.memory_provider import MemoryProvider  # noqa: E402,F401
except ImportError:
    MemoryProvider = object  # type: ignore


_ATLAS_HOME = _Path.home() / ".hermes" / "atlas"


def register(ctx):
    """Hermes plugin contract — register ATLAS as memory provider.

    Hermes calls register(ctx) where ctx is a _ProviderCollector with
    ctx.register_memory_provider(provider) method.
    """
    try:
        # ATLAS backend: HybridMemoryEngine + Orchestrator
        from loop_memory.engine import HybridMemoryEngine
        from loop_memory.orchestrator import MemoryOrchestrator

        _ATLAS_HOME.mkdir(parents=True, exist_ok=True)

        engine = HybridMemoryEngine.create_default(
            db_path=str(_ATLAS_HOME / "atlas.db"),
            qdrant_location=str(_ATLAS_HOME / "qdrant"),
        )
        orchestrator = MemoryOrchestrator(engine=engine)

        provider = AtlasMemoryProvider(orchestrator=orchestrator)
        ctx.register_memory_provider(provider)
    except Exception as exc:
        import logging
        logging.getLogger("atlas-plugin").warning("ATLAS register failed: %s", exc)
        # Fallback: register bare provider (functional passthrough)
        ctx.register_memory_provider(AtlasMemoryProvider())

PYTHON

# Podstaw realne ścieżki (H4: zero hardcoded wartości)
SITE_PACKAGES=$("$PYTHON" -c 'import site; print(site.getsitepackages()[0])')
sed -i "s|__HERMES_PYTHON__|${PYTHON}|g" "${PLUGIN_DIR}/__init__.py"
sed -i "s|__HERMES_SITE__|${SITE_PACKAGES}|g" "${PLUGIN_DIR}/__init__.py"
sed -i "s|__ATLAS_SRC__|${REPO_ROOT}/src|g" "${PLUGIN_DIR}/__init__.py"

log "✓ Wrapper wygenerowany"

# --- 2. Aktywuj jeśli zażądano
if [[ $ACTIVATE -eq 1 ]]; then
  log "Aktywacja providera w Hermes config..."
  if command -v hermes >/dev/null 2>&1; then
    hermes config set memory.provider atlas
    log "✓ memory.provider = atlas"
  else
    log "⚠ hermes CLI nie w PATH — ustaw ręcznie: memory.provider: atlas w ~/.hermes/config.yaml"
  fi
fi

# --- 3. Weryfikacja
log "Weryfikacja..."
"$PYTHON" - <<'PYCHECK'
import sys
from pathlib import Path

# Symulacja Hermes plugin loader
plugins_root = Path.home() / ".hermes" / "plugins"
if str(plugins_root) not in sys.path:
    sys.path.append(str(plugins_root))

try:
    # 1. Sprawdź discovery przez hermes provider collector
    try:
        from plugins.memory import discover_memory_providers, load_memory_provider
        providers = discover_memory_providers()
        names = [p[0] for p in providers]
        print(f"  discover: atlas ∈ {len(names)} providers")
        
        provider = load_memory_provider("atlas")
        if provider:
            avail = provider.is_available()
            print(f"  load: atlas, available={avail}")
        else:
            print("  load: atlas -> FAILED (None)")
            sys.exit(1)
    except ImportError:
        # Standalone check bez pełnego hermes-agent w PATH
        import importlib
        mod = importlib.import_module("atlas")
        print(f"  import atlas: OK ({mod.__file__})")

    print("→ ✓ Instalacja OK")
except Exception as e:
    print(f"✗ Weryfikacja nie powiodła się: {e}")
    sys.exit(1)
PYCHECK

echo ""
echo "═══════════════════════════════════════════════════════════"
echo " ATLAS plugin zainstalowany pomyślnie"
echo "═══════════════════════════════════════════════════════════"
echo "  Plugin dir: ${PLUGIN_DIR}"
echo "  Izolacja:   ATLAS silnik działa w Pixi (.pixi/envs/default)"
echo "  Config:     ~/.hermes/config.yaml (memory.provider)"
echo ""
echo "  Aby aktywować:  hermes config set memory.provider atlas"
echo "  Aby odinstalować: bash $0 --uninstall"
echo "  Aby zweryfikować: hermes memory status"
echo ""
